Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 55, in <module>
    WebDriverWait(driver, 30).until(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5600fb0758fa <unknown>
#1 0x5600fab86d20 <unknown>
#2 0x5600fabd5a66 <unknown>
#3 0x5600fabd5d01 <unknown>
#4 0x5600fac1b184 <unknown>
#5 0x5600fabf9b1d <unknown>
#6 0x5600fac18560 <unknown>
#7 0x5600fabf9893 <unknown>
#8 0x5600fabc830d <unknown>
#9 0x5600fabc932e <unknown>
#10 0x5600fb04200b <unknown>
#11 0x5600fb045f97 <unknown>
#12 0x5600fb02e71c <unknown>
#13 0x5600fb046b17 <unknown>
#14 0x5600fb0136cf <unknown>
#15 0x5600fb0646b8 <unknown>
#16 0x5600fb064880 <unknown>
#17 0x5600fb074776 <unknown>
#18 0x7f64e9737ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 55, in <module>
    WebDriverWait(driver, 30).until(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556165d758fa <unknown>
#1 0x556165886d20 <unknown>
#2 0x5561658d5a66 <unknown>
#3 0x5561658d5d01 <unknown>
#4 0x55616591b184 <unknown>
#5 0x5561658f9b1d <unknown>
#6 0x556165918560 <unknown>
#7 0x5561658f9893 <unknown>
#8 0x5561658c830d <unknown>
#9 0x5561658c932e <unknown>
#10 0x556165d4200b <unknown>
#11 0x556165d45f97 <unknown>
#12 0x556165d2e71c <unknown>
#13 0x556165d46b17 <unknown>
#14 0x556165d136cf <unknown>
#15 0x556165d646b8 <unknown>
#16 0x556165d64880 <unknown>
#17 0x556165d74776 <unknown>
#18 0x7f0dbd184ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 55, in <module>
    WebDriverWait(driver, 30).until(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563cab2818fa <unknown>
#1 0x563caad92d20 <unknown>
#2 0x563caade1a66 <unknown>
#3 0x563caade1d01 <unknown>
#4 0x563caae27184 <unknown>
#5 0x563caae05b1d <unknown>
#6 0x563caae24560 <unknown>
#7 0x563caae05893 <unknown>
#8 0x563caadd430d <unknown>
#9 0x563caadd532e <unknown>
#10 0x563cab24e00b <unknown>
#11 0x563cab251f97 <unknown>
#12 0x563cab23a71c <unknown>
#13 0x563cab252b17 <unknown>
#14 0x563cab21f6cf <unknown>
#15 0x563cab2706b8 <unknown>
#16 0x563cab270880 <unknown>
#17 0x563cab280776 <unknown>
#18 0x7f9c7d404ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 55, in <module>
    WebDriverWait(driver, 30).until(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55a5c78ab8fa <unknown>
#1 0x55a5c73bcd20 <unknown>
#2 0x55a5c740ba66 <unknown>
#3 0x55a5c740bd01 <unknown>
#4 0x55a5c7451184 <unknown>
#5 0x55a5c742fb1d <unknown>
#6 0x55a5c744e560 <unknown>
#7 0x55a5c742f893 <unknown>
#8 0x55a5c73fe30d <unknown>
#9 0x55a5c73ff32e <unknown>
#10 0x55a5c787800b <unknown>
#11 0x55a5c787bf97 <unknown>
#12 0x55a5c786471c <unknown>
#13 0x55a5c787cb17 <unknown>
#14 0x55a5c78496cf <unknown>
#15 0x55a5c789a6b8 <unknown>
#16 0x55a5c789a880 <unknown>
#17 0x55a5c78aa776 <unknown>
#18 0x7fb2d58daac3 <unknown>

No link found.
Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 185, in <module>
    if date==date_format(datetime.now().today()):
NameError: name 'date' is not defined
No link found.
Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 185, in <module>
    if date==date_format(datetime.now().today()):
NameError: name 'date' is not defined
No link found.
Traceback (most recent call last):
  File "/root/news_site_scraper/shangri.py", line 185, in <module>
    if date==date_format(datetime.now().today()):
NameError: name 'date' is not defined
